[package]
name = "tiny-apng"
version = "0.0.1"
authors = ["anekos <anekos@snca.net>"]
edition = "2018"

[dependencies]
flate2 = "*"
byteorder = "*"

[dev-dependencies]
image = "*"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy"]
