on: [push, pull_request]

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
      - run: |
          sudo apt-get install tree
          tree
      - uses: actions/upload-artifact@v2
        with:
          path: build/release/
