on: [push, pull_request]

jobs:
  build-lib:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: lib-${{ runner.os }}
          path: target/release/*apng*.*

  build-apng:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo build --release
        working-directory: ./example
      - uses: actions/upload-artifact@v2
        with:
          name: apngc-${{ runner.os }}
          path: example/target/release/*apng*.*

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --verbose --all
